joomla:
  image: joomla
  links:
    - joomladb:mysql
  ports:
    - 8080:80
  volumes:
    - ~/joomla/joomla_html:/var/www/html

joomladb:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: example
  volumes:
    - ~/joomla/joomla_mysql:/var/lib/mysql